feminino(mum).
feminino(kydd).
feminino(elizabeth).
feminino(margaret).
feminino(diana).
feminino(anne).
feminino(sarah).
feminino(zara).
feminino(beatrice).
feminino(eugenie).
masculino(george).
masculino(spencer).
masculino(philip).
masculino(charles).
masculino(mark).
masculino(andrew).
masculino(edward).
masculino(william).
masculino(harry).
masculino(peter).
conjuge(george,mum).
conjuge(spencer,kidd).
conjuge(philip,elizabeth).
conjuge(charles,diana).
conjuge(mark,anne).
conjuge(andrew,sarah).
genitor(george,elizabeth).
genitor(george,margaret).
genitor(mum,elizabeth).
genitor(mum,margaret).
genitor(spencer,diana).
genitor(kydd,diana).
genitor(elizabeth,charles).
genitor(elizabeth,anne).
genitor(elizabeth,andrew).
genitor(elizabeth,edward).
genitor(philip,charles).
genitor(philip,anne).
genitor(philip,andrew).
genitor(philip,edward).
genitor(diana,william).
genitor(diana,harry).
genitor(charles,william).
genitor(charles,harry).
genitor(anne,peter).
genitor(anne,zara).
genitor(mark,peter).
genitor(mark,zara).
genitor(andrew,beatrice).
genitor(andrew,eugenie).
genitor(sarah,beatrice).
genitor(sarah,eugenie).
casados(X,Y):-conjuge(X,Y);conjuge(Y,X).
esposo(X):-casados(X,Y),masculino(X).
esposa(X):-casados(X,Y),feminino(X).
mae(X):-genitor(X,Y),feminino(X).
pai(X):-genitor(X,Y),masculino(X).
filha(X):-genitor(Y,X),feminino(X).
filho(X):-genitor(Y,X),masculino(X).
irmao(X,Y):-genitor(Z,X),genitor(Z,Y),masculino(X).
irma(X,Y):-genitor(Z,X),genitor(Z,Y),feminino(X).
avo(X,Y):-genitor(X,Z),genitor(Z,Y),masculino(X).
avoh(X,Y):-genitor(X,Z),genitor(Z,Y),feminino(X).
tia(X,Y):-genitor(Z,Y),irma(X,Z).
tio(X,Y):-genitor(Z,Y),irmao(X,Z).
primo(X,Y):-genitor(Z,Y),masculino(X),(tio(Z,X);tia(Z,X)).
prima(X,Y):-genitor(Z,Y),feminino(X),(tio(Z,X);tia(Z,X)).
cunhado(X,Y):-casados(X,Z),masculino(X),(irmao(Z,Y);irma(Z,Y)).
cunhado(X,Y):-irmao(X,Z),casados(Y,Z).
cunhada(X,Y):-casados(X,Z),feminino(X),(irmao(Z,Y);irma(Z,Y)).
cunhada(X,Y):-irma(X,Z),casados(Y,Z).
neto(X,Y):-masculino(X),(avo(Y,X);avoh(Y,X)).
neta(X,Y):-feminino(X),(avo(Y,X);avoh(Y,X)).
descendente(X,Y):-genitor(Y,X).
descendente(X,Y):-genitor(Y,Z),descendente(X,Z).