/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExibirCliente.java
 *
 * Created on 29/10/2010, 13:59:32
 */

package vendainterface;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilitarios.LtpUtil;
import vendacontrole.Cliente;
import vendacontrole.Principal;
import vendacontrole.Produto;
import vendacontrole.Venda;

/**
 *
 * @author Giovanne
 */
public class ExibirVenda extends javax.swing.JFrame {
    private static Connection con;
    private static Principal portControl = new Principal();

    /** Creates new form ExibirCliente */
    public ExibirVenda() {
        initComponents();
        limpaform();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar8 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jPanelClientePrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextCodVendedor = new javax.swing.JTextField();
        jTextFieldCodCliente = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jButtonBuscarCodigo = new javax.swing.JButton();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar6.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar6.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar7.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar7.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar8.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar8.add(jMenu14);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("CodVendedor:");

        jLabel3.setText("Cod. Cliente:");

        jLabel10.setText("Data:");

        jTextFieldCodigo.setEditable(false);

        jTextCodVendedor.setEnabled(false);

        jTextFieldCodCliente.setEditable(false);

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jButtonBuscarCodigo.setText("Buscar");
        jButtonBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCodigoActionPerformed(evt);
            }
        });

        jButtonPrimeiro.setText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setText("Ultimo");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonAnterior.setText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClientePrincipalLayout = new javax.swing.GroupLayout(jPanelClientePrincipal);
        jPanelClientePrincipal.setLayout(jPanelClientePrincipalLayout);
        jPanelClientePrincipalLayout.setHorizontalGroup(
            jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientePrincipalLayout.createSequentialGroup()
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientePrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelClientePrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addGap(22, 22, 22)
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelClientePrincipalLayout.createSequentialGroup()
                        .addComponent(jButtonAlterar)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonIncluir))
                    .addGroup(jPanelClientePrincipalLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButtonBuscarCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir))
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelClientePrincipalLayout.createSequentialGroup()
                        .addComponent(jButtonPrimeiro)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProximo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUltimo))
                    .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextCodVendedor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelClientePrincipalLayout.setVerticalGroup(
            jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonIncluir)
                        .addComponent(jButtonBuscarCodigo)
                        .addComponent(jButtonExcluir))
                    .addComponent(jButtonAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextCodVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(47, 47, 47)
                .addGroup(jPanelClientePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonUltimo))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanelClientePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jPanelClientePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        // TODO add your handling code here:
        try {

            //Produto objProduto = portControl.ConsultarProdutoUltimo();
            new IncluirVenda(this);
            //exibirProduto(objProduto);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }




        
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jMenuItemConsultaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaNomeActionPerformed
        // TODO add your handling code here:
         new PesqProdutoNome(this);
         
    }//GEN-LAST:event_jMenuItemConsultaNomeActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        try {
            Venda objVenda = portControl.ConsultarVendaUltimo();

            exibirVenda(objVenda);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        try {
            if(jTextFieldCodigo.getText().equals("")){
                Venda objVenda = portControl.ConsultarVendaUltimo();

                exibirVenda(objVenda);
            }else{
                Venda objVenda = portControl.ConsultarVendaProximo(Integer.parseInt(jTextFieldCodigo.getText()));

                exibirVenda(objVenda);
            }


        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        try {
            if(jTextFieldCodigo.getText().equals("")){
                Venda objVenda = portControl.ConsultarVendaPrimeiro();
                
                exibirVenda(objVenda);
            }else{
                Venda objVenda = portControl.ConsultarVendaAnterior(Integer.parseInt(jTextFieldCodigo.getText()));
                
                exibirVenda(objVenda);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        try {
            //Produto objProduto = portControl.ConsultarProdutoPrimeiro();
            Venda objVenda = portControl.ConsultarVendaPrimeiro();
            
            exibirVenda(objVenda);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if(jTextFieldCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Defina a Venda","Defina a Venda",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if ( JOptionPane.showConfirmDialog(null, "Confirmar a exclusão da Venda - " +
                Integer.parseInt(jTextFieldCodigo.getText()) + " ?" ,
                "Cadastro de Venda",
                JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION ){
            return;
        }
        try {
            portControl.excluirVenda(Integer.parseInt(jTextFieldCodigo.getText()));
            JOptionPane.showMessageDialog(this,"Venda Excluída","Venda",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }
        limpaform();

}//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCodigoActionPerformed

        String codigo = JOptionPane.showInputDialog(
                this,
                "Código da Venda",
                "Consulta de Vendas",
                JOptionPane.QUESTION_MESSAGE);
        if (codigo == null) return;
        if (codigo.trim().equals("") ||
                !codigo.matches("[0-9]*")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Código Inválido.",
                    "Consulta de Vendas",
                    JOptionPane.WARNING_MESSAGE);
        }

        Venda objVenda;
        try {
            objVenda = portControl.consultarVendaCodigo(Integer.parseInt(codigo));
            
            exibirVenda(objVenda);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarCodigoActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed


        if (jTextFieldCodigo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Não Alterado","Consulta de Cliente",JOptionPane.WARNING_MESSAGE);
        }else{

        
        // TODO add your handling code here:
        Venda objVendaIncluir =
                new Venda(Integer.parseInt((jTextFieldCodigo.getText())),
                            Integer.parseInt(jTextCodVendedor.getText()),
                            Integer.parseInt((jTextFieldCodCliente.getText())),
                            new GregorianCalendar() );

        try {
            portControl.alteraVenda(objVendaIncluir);
            JOptionPane.showMessageDialog(this,"Venda Atualizado","Venda Atualizado",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Consulta de Venda",JOptionPane.WARNING_MESSAGE);
        }
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirVenda().setVisible(true);
                try {
                    // TODO add your handling code here:
                    con = portControl.conectar();
                } catch (SQLException ex) {
                    Logger.getLogger(ExibirCliente.class.getName()).log(Level.SEVERE, null, ex);
                }





            }
        });
    }
    private void exibirVenda(Venda objVenda){
             
            // TODO add your handling code here:


            jTextFieldCodigo.setText(""+objVenda.getCodVenda());
            //jTextFieldCodigo.setEditable(false);
            jTextCodVendedor.setText(""+objVenda.getCodVendedor());
            jTextFieldCodCliente.setText(""+objVenda.getCodCliente());
            
            jFormattedTextFieldData.setText(LtpUtil.formatarData(objVenda.getData_venda(), "dd/MM/yyyy"));

            //jFormattedTextFieldData.setText(objCliente.getData_cad_cliente().toString());





    }
    private void limpaform(){
            jTextCodVendedor.setText("");
            jTextFieldCodCliente.setText("");
            jTextFieldCodigo.setText("");
            jFormattedTextFieldData.setText("");


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonBuscarCodigo;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar jMenuBar8;
    private javax.swing.JPanel jPanelClientePrincipal;
    private javax.swing.JTextField jTextCodVendedor;
    private javax.swing.JTextField jTextFieldCodCliente;
    private javax.swing.JTextField jTextFieldCodigo;
    // End of variables declaration//GEN-END:variables

}
